# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
snapshot:
  version_template: 0.0.0-snapshot

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - main: ./cmd/lsgo/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
dockers_v2:
  - images:
      - "ghcr.io/mszalbach/lsgo"
    tags:
      - "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
    ids:
      - lsgo
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^ci:"
      - "merge conflict"
      - Merge pull request
      - Merge branch
  groups: # Regex use RE2 syntax as defined here: https://github.com/google/re2/wiki/Syntax.
    - title: "Breaking Changes"
      regexp: '^.*?(\([[:word:]]+\))??!:.+$'
      order: 0
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 300
    - title: "Dependency updates"
      regexp: '^.*?(feat|fix|chore)\(deps?.+\)!?:.+$'
      order: 400
    - title: "Other work"
      order: 999
sboms:
  - args: ["$artifact", "--output", "cyclonedx-json=$document"]

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
