# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
snapshot:
  version_template: 0.0.0-snapshot 

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - main: ./cmd/lsgo/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
dockers_v2:
  - images:
      - "ghcr.io/mszalbach/lsgo"
    tags:
      - "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
    ids:
      - lsgo
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "merge conflict"
      - Merge pull request
      - Merge branch
  groups:
    - title: "Features"
      regexp: '^feat[(\w\s)]*:'
      order: 0
    - title: "Bug Fixes"
      regexp: '^fix[(\w\s)]*:'
      order: 1
    - title: "Maintenance & Refactoring"
      regexp: '^refactor[(\w\s)]*:'
      order: 2
    - title: "Other Changes"
      order: 999
sboms:
  - args: ["$artifact", "--output", "cyclonedx-json=$document"]

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
