name: CI Pipeline
permissions:
  contents: read
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version: "1.27.1"
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.4.1

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v7.2.3
        with:
          install-only: true

      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          version: v2.13.2
          install-only: true

      - name: Run golangci-lint
        run: make lint-ci

      - name: Run Tests
        run: make test

      - name: Run Govulncheck
        uses: golang/govulncheck-action@v1.1.0
        with:
          repo-checkout: false

      - name: Verify Build
        run: make build

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - qa
    permissions:
      actions: read # needed for sbom task to see the release
      contents: write # needed by goreleaser to write release to github
      packages: write # needed by goreleaser to upload docker
    runs-on: ubuntu-latest
    steps:
      - name: heckout repository
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0 # needed for goreleaser to correctly create changelog

      - name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version: "1.27.1"
          cache: true

      - name: Set up Syft
        uses: anchore/sbom-action/download-syft@v0.24.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.4.1

      - name: Log in to GHCR
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7.2.3
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
