name: Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "preview without publishing"
        required: true
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v7.1.0
        with:
          dry_run: ${{ inputs.dry_run }}
          skip_npm_plugin: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
