name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Semantic Release
        uses: go-semantic-release/action@v1.24.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}